#!/usr/bin/env python3
import os
import py_compile

filename = os.environ.get('PYFILE')

compiled_filename = f"{filename[:-3]}c"

print(f"Compiling {filename} ...")

py_compile.compile(filename, compiled_filename)

print("Compilation complete.")